const EmpData=[
    {
      "empno":1231,
      "name":"Dharmendra",
     "designation":"Indore",
     "salary":80000
    },
    {
      "empno":1232,
      "name":"Amit",
     "designation":"jabalpur",
     "salary":70000
    },
    {
      "empno":1243,
      "name":"avnish",
     "designation":"Reva",
     "salary":30000
    },
    {
      "empno":1234,
      "name":"harsh",
     "designation":"Satna",
     "salary":40000
    },
    {
      "empno":1235,
      "name":"Raju",
     "designation":"Nagpur",
     "salary":50000
    },
    {
      "empno":1236,
      "name":"harshit",
     "designation":"Bihar",
     "salary":60000
    }
  ]

  export default  EmpData;